//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Express_Solution
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public string nom_utilisateur_pk { get; set; }
        public string mot_passe_utilisateur { get; set; }
        public string role_utilisateur { get; set; }
        public Nullable<int> id_employe_fk { get; set; }
        public Nullable<System.DateTime> date_heure_derniere_connexion_utilisateur { get; set; }
        public System.DateTime C_row_insert_datetime { get; set; }
        public Nullable<System.DateTime> C_row_update_datetime { get; set; }
        public Nullable<System.DateTime> C_row_delete_datetime { get; set; }
    
        public virtual employe employe { get; set; }
    }
}
