//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCD_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Contrats = new HashSet<Contrat>();
            this.Contrats1 = new HashSet<Contrat>();
            this.Reservations = new HashSet<Reservation>();
            this.Reservations1 = new HashSet<Reservation>();
        }
    
        public int id_client_pk { get; set; }
        public byte[] photo_client { get; set; }
        public string nom_client { get; set; }
        public string prenom_client { get; set; }
        public string nationalite_client { get; set; }
        public Nullable<System.DateTime> date_naissance_client { get; set; }
        public string lieu_naissance_client { get; set; }
        public string adresse_domicile_client { get; set; }
        public string ville_domicile_client { get; set; }
        public string code_postal_domicile_client { get; set; }
        public string adresse_residence_client { get; set; }
        public string ville_residence_client { get; set; }
        public string code_postal_residence_client { get; set; }
        public string telephone_portable_client { get; set; }
        public string telephone_fixe_client { get; set; }
        public string fax_client { get; set; }
        public string email_client { get; set; }
        public string type_client { get; set; }
        public string id_national_client { get; set; }
        public string type_id_national_client { get; set; }
        public Nullable<System.DateTime> date_heure_delivraison_id_national_client { get; set; }
        public string lieu_delivraison_id_national_client { get; set; }
        public string id_permis_conduire_client { get; set; }
        public Nullable<System.DateTime> date_heure_delivraison_permis_client { get; set; }
        public string lieu_delivraison_permis_Client { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrat> Contrats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrat> Contrats1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations1 { get; set; }
    }
}
