//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCD_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrat
    {
        public int id_contrat_pk { get; set; }
        public Nullable<int> id_client_fk { get; set; }
        public string immatriculation_vehicule_fk { get; set; }
        public Nullable<int> id_client_compagnon_fk { get; set; }
        public Nullable<int> id_employe_conducteur_fk { get; set; }
        public string description_equipements_speciaux_contrat { get; set; }
        public Nullable<System.DateTime> date_heure_depart_vehicule_contrat { get; set; }
        public Nullable<System.DateTime> date_heure_retour_vehicule_contrat { get; set; }
        public string lieu_depart_vehicule_contrat { get; set; }
        public string lieu_retour_vehicule_contrat { get; set; }
        public Nullable<decimal> frais_conducteur_contrat { get; set; }
        public Nullable<decimal> frais_equipements_speciaux_contrat { get; set; }
        public Nullable<decimal> montant_forfait_contrat { get; set; }
        public Nullable<decimal> montant_remise_contrat { get; set; }
        public string mode_paiement_contrat { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual Employe Employe { get; set; }
        public virtual Vehicule Vehicule { get; set; }
    }
}
