//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCD_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public string nom_utilisateur_pk { get; set; }
        public string mot_passe_utilisateur { get; set; }
        public byte[] photo_utilisateur { get; set; }
        public string role_utilisateur { get; set; }
        public Nullable<System.DateTime> date_heure_derniere_connexion_utilisateur { get; set; }
    }
}
