//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCD_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicule()
        {
            this.Contrats = new HashSet<Contrat>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public string immatriculation_vehicule_pk { get; set; }
        public byte[] photo_vehicule { get; set; }
        public string type_vehicule { get; set; }
        public string marque_vehicule { get; set; }
        public string description_vehicule { get; set; }
        public Nullable<double> distance_parcourue_vehicule { get; set; }
        public string type_energie_vehicule { get; set; }
        public Nullable<double> quantite_energie_vehicule { get; set; }
        public Nullable<decimal> prix_location_vehicule { get; set; }
        public Nullable<System.DateTime> date_achat_vehicule { get; set; }
        public Nullable<System.DateTime> date_derniere_maintenance_vehicule { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrat> Contrats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
